FROM python:3.10.2-buster

WORKDIR /usr/src/notification_scheduler

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./requirements.txt ./

RUN pip install -r ./requirements.txt

# Create a non-root user
RUN useradd -m celery_user
RUN chown -R celery_user:celery_user /usr/src/notification_scheduler

USER celery_user

CMD cd .. && celery -A notification_scheduler worker --loglevel=debug --concurrency=10