FROM python:3.10.2-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY ./requirements.test.txt ./

RUN pip install -r ./requirements.test.txt

CMD pytest